export const MLS_RULES = {
  seasonStartYear: 2026,
  clubs: 30,
  matchesPerTeam: 34,
  playoffQualifiersPerConference: 9,
  salaryBudget: 6425000,
  maxBudgetCharge: 803125,
  youngDpBudgetU20: 150000,
  youngDpBudgetU23: 200000,
  gamAnnual: 3280000,
  tamAnnual: 2125000,
  intlSlotsDefault: 8,
};

export const CONFERENCES = {
  East: [
    "Atlanta United",
    "Charlotte FC",
    "Chicago Fire FC",
    "FC Cincinnati",
    "Columbus Crew",
    "D.C. United",
    "Inter Miami CF",
    "CF Montréal",
    "Nashville SC",
    "New England Revolution",
    "New York City FC",
    "New York Red Bulls",
    "Orlando City SC",
    "Philadelphia Union",
    "Toronto FC",
  ],
  West: [
    "Austin FC",
    "Colorado Rapids",
    "FC Dallas",
    "Houston Dynamo FC",
    "Sporting Kansas City",
    "LA Galaxy",
    "Los Angeles FC",
    "Minnesota United FC",
    "Portland Timbers",
    "Real Salt Lake",
    "San Diego FC",
    "San Jose Earthquakes",
    "Seattle Sounders FC",
    "St. Louis CITY SC",
    "Vancouver Whitecaps FC",
  ],
};

export const RIVALRIES = [
  ["LA Galaxy", "Los Angeles FC"],
  ["Seattle Sounders FC", "Portland Timbers"],
  ["New York City FC", "New York Red Bulls"],
  ["FC Dallas", "Houston Dynamo FC"],
  ["Columbus Crew", "FC Cincinnati"],
  ["Inter Miami CF", "Orlando City SC"],
  ["Toronto FC", "CF Montréal"],
];

export const POSITIONS = ["GK", "LB", "CB", "RB", "LM", "RM", "CDM", "CM", "CAM", "LW", "RW", "ST"];

export const TEAM_LOGOS = {
  "Atlanta United": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747499879/assets/logos/mls-clubs/Club_Logo-Atlanta_jtk7ku.png",
  "Austin FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747499975/assets/logos/mls-clubs/Club_Logo-Austin_pa9xtu.png",
  "Charlotte FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747500045/assets/logos/mls-clubs/Club_Logo-Charlotte_p7sznf.png",
  "Chicago Fire FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747500178/assets/logos/mls-clubs/Club_Logo-Chicago_jm2yev.png",
  "FC Cincinnati": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747500249/assets/logos/mls-clubs/Club_Logo-Cincinnati_jwgkps.png",
  "Colorado Rapids": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747500322/assets/logos/mls-clubs/Club_Logo-Colorado_n5kpss.png",
  "Columbus Crew": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747500414/assets/logos/mls-clubs/Club_Logo-Columbus_light_z3eq8l.png",
  "D.C. United": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747500504/assets/logos/mls-clubs/Club_Logo-D.C_t03ekm.png",
  "FC Dallas": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747500567/assets/logos/mls-clubs/Club_Logo-Dallas_sysmtj.png",
  "Houston Dynamo FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747500939/assets/logos/mls-clubs/Club_Logo-Houston_oifm77.png",
  "Sporting Kansas City": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747754918/assets/logos/mls-clubs/Club_Logo-Kansas_City_cnhd75.png",
  "LA Galaxy": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747755165/assets/logos/mls-clubs/Club_Logo-LA_Galaxy_fg0wjp.png",
  "Los Angeles FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747755309/assets/logos/mls-clubs/Club_Logo-LAFC_djrhru.png",
  "Inter Miami CF": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747755405/assets/logos/mls-clubs/Club_Logo-Miami_tyqe64.png",
  "Minnesota United FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747754826/assets/logos/mls-clubs/Club_Logo-Minnesota_ftweor.png",
  "CF Montréal": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747755806/assets/logos/mls-clubs/Club_Logo-Montreal_beeqnh.png",
  "Nashville SC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747755999/assets/logos/mls-clubs/Club_Logo-Nashville_rb9vwu.png",
  "New England Revolution": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1766020750/assets/NE_Logo_PRI_FC_RGB_480x480_fdx2us.png",
  "New York Red Bulls": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1745380974/assets/mnp/club-logos/399-ny-red-bulls-logo_o6xw9r_mdsm9e.png",
  "New York City FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747756306/assets/logos/mls-clubs/Club_Logo-New_York_City_xu6vax.png",
  "Orlando City SC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747769281/assets/logos/mls-clubs/Club_Logo-Orlando_ryyn7a.png",
  "Philadelphia Union": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747769446/assets/logos/mls-clubs/Club_Logo-Philadelphia_im7pqg.png",
  "Portland Timbers": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747769540/assets/logos/mls-clubs/Club_Logo-Portland_qihpaz.png",
  "Real Salt Lake": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747776403/assets/logos/mls-clubs/Club_Logo-Salt_Lake_City_hpvde5.png",
  "San Diego FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1748261519/assets/logos/mls-clubs/Club_Logo-San_Diego_nwpyul.png",
  "San Jose Earthquakes": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1748262048/assets/logos/mls-clubs/Club_Logo-San_Jose_opzlmo.png",
  "Seattle Sounders FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1748265125/assets/logos/mls-clubs/Club_Logo-Seattle_e6jk2x.png",
  "St. Louis CITY SC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1747771858/assets/logos/mls-clubs/Club_Logo-Saint_Louis_guz12c.png",
  "Toronto FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1748265251/assets/logos/mls-clubs/Club_Logo-Toronto_vz6hao.png",
  "Vancouver Whitecaps FC": "https://images.mlssoccer.com/image/upload/t_club_logo_medium/v1748265547/assets/logos/mls-clubs/Club_Logo-Vancouver_ao9phl.png",
};



export const TEAM_COLORS = {
  "Atlanta United": { primary: "#A19060", secondary: "#80000A", text: "#111111" },
  "Austin FC": { primary: "#00B140", secondary: "#111111", text: "#111111" },
  "Charlotte FC": { primary: "#1A85C8", secondary: "#111111", text: "#ffffff" },
  "Chicago Fire FC": { primary: "#6BA4FF", secondary: "#A90F2F", text: "#ffffff" },
  "FC Cincinnati": { primary: "#0C1F3F", secondary: "#F37021", text: "#ffffff" },
  "Colorado Rapids": { primary: "#862633", secondary: "#9EA2A2", text: "#ffffff" },
  "Columbus Crew": { primary: "#FFDD00", secondary: "#111111", text: "#111111" },
  "D.C. United": { primary: "#111111", secondary: "#CF132B", text: "#ffffff" },
  "FC Dallas": { primary: "#E31C3D", secondary: "#0B1F41", text: "#ffffff" },
  "Houston Dynamo FC": { primary: "#F37021", secondary: "#111111", text: "#111111" },
  "Sporting Kansas City": { primary: "#6AB2E7", secondary: "#0B1F41", text: "#ffffff" },
  "LA Galaxy": { primary: "#00245D", secondary: "#FFB81C", text: "#ffffff" },
  "Los Angeles FC": { primary: "#111111", secondary: "#C6A663", text: "#ffffff" },
  "Inter Miami CF": { primary: "#F7B5CD", secondary: "#111111", text: "#111111" },
  "Minnesota United FC": { primary: "#7E8AA2", secondary: "#93C1E5", text: "#111111" },
  "CF Montréal": { primary: "#0F1C35", secondary: "#78A7D8", text: "#ffffff" },
  "Nashville SC": { primary: "#ECE83A", secondary: "#162B75", text: "#111111" },
  "New England Revolution": { primary: "#0B1F41", secondary: "#E1261C", text: "#ffffff" },
  "New York Red Bulls": { primary: "#D71920", secondary: "#1A1A1A", text: "#ffffff" },
  "New York City FC": { primary: "#6CADDF", secondary: "#0B1F41", text: "#111111" },
  "Orlando City SC": { primary: "#633492", secondary: "#FAD64A", text: "#ffffff" },
  "Philadelphia Union": { primary: "#0B1F41", secondary: "#C89A2D", text: "#ffffff" },
  "Portland Timbers": { primary: "#004812", secondary: "#D69A3D", text: "#ffffff" },
  "Real Salt Lake": { primary: "#9D2235", secondary: "#FDB913", text: "#ffffff" },
  "San Diego FC": { primary: "#00B0E6", secondary: "#111111", text: "#111111" },
  "San Jose Earthquakes": { primary: "#0B1F41", secondary: "#0077C8", text: "#ffffff" },
  "Seattle Sounders FC": { primary: "#5D9741", secondary: "#005595", text: "#111111" },
  "St. Louis CITY SC": { primary: "#D61A5E", secondary: "#0B1F41", text: "#ffffff" },
  "Toronto FC": { primary: "#D71920", secondary: "#3B3B3B", text: "#ffffff" },
  "Vancouver Whitecaps FC": { primary: "#0B1F41", secondary: "#7A8A9E", text: "#ffffff" },
};

export const US_OPEN_CUP_MLS_2026 = [
  "Atlanta United", "Austin FC", "Charlotte FC", "Chicago Fire FC", "Colorado Rapids",
  "Columbus Crew", "D.C. United", "Houston Dynamo FC", "Minnesota United FC",
  "New England Revolution", "New York City FC", "Orlando City SC", "New York Red Bulls",
  "San Jose Earthquakes", "St. Louis CITY SC", "Sporting Kansas City"
];

export const US_OPEN_CUP_OPEN_FIELD_2026 = [
  "Asheville City SC", "Des Moines Menace", "El Farolito", "FC Motown", "Flint City Bucks",
  "Flower City Union", "Hickory FC", "Laredo Heat SC", "Little Rock Rangers", "Michigan Rangers",
  "Northern Virginia FC", "Ristozi FC", "Tennessee Tempo FC", "Ventura County Fusion",
  "Vermont Green FC", "West Chester United SC"
];

export const NATIONS = [
  "USA", "Canada", "Mexico", "Argentina", "Brazil", "Colombia", "Uruguay", "Paraguay", "Chile", "Peru",
  "Venezuela", "Ecuador", "Bolivia", "Costa Rica", "Honduras", "Panama", "Jamaica", "Haiti", "Dominican Republic",
  "England", "Scotland", "Ireland", "Wales", "France", "Spain", "Portugal", "Germany", "Netherlands", "Belgium",
  "Italy", "Switzerland", "Austria", "Denmark", "Sweden", "Norway", "Croatia", "Serbia", "Bosnia and Herzegovina",
  "Poland", "Czech Republic", "Ukraine", "Romania", "Turkey", "Morocco", "Algeria", "Tunisia", "Egypt",
  "Nigeria", "Ghana", "Ivory Coast", "Senegal", "Cameroon", "Mali", "Japan", "South Korea", "Australia", "New Zealand",
  "Israel", "Iran", "Georgia", "Armenia", "India"
];

export const FIRST_NAMES = [
  "Alex","Jordan","Mateo","Diego","Luca","Leo","Noah","Ethan","Julian","Marco","Thiago",
  "Dylan","Gabriel","Daniel","Ben","Chris","Owen","David","Nathan","Tyler","Miguel",
  "Jose","Andres","Emilio","Sebastian","Luis","Carlos","Javier","Felix","Roman","Niko",
  "Mason","Aiden","Logan","Isaac","Pablo","Victor","Bruno","Enzo","Rafael","Adrian"
];

export const LAST_NAMES = [
  "Smith","Jones","Clark","Miller","Johnson","Garcia","Lopez","Martinez","Silva",
  "Santos","Alvarez","Romero","Gomez","Herrera","Ortiz","Vega","Morales","Diaz",
  "Fernandez","Torres","Ramirez","Pereira","Costa","Mendes","Rossi","Moreira",
  "Ibrahim","Okafor","Mensah","Petrovic","Kovacic","Jansen","Andersson","Svensson",
  "Kim","Tanaka","Yamamoto","Brown","White","Wright","Hall","Green","Bennett"
];

export const COLLEGES = [
  "Maryland",
  "UCLA",
  "Wake Forest",
  "Indiana",
  "North Carolina",
  "Virginia",
  "Creighton",
  "Duke",
  "Akron",
  "Syracuse",
  "Georgetown",
  "St. Louis",
  "Notre Dame",
  "Penn State",
  "SMU",
  "Stanford",
  "Clemson",
  "Oregon State",
  "New Hampshire",
  "Kentucky",
  "Louisville",
  "Michigan State",
  "Michigan",
  "Ohio State",
  "Wisconsin",
  "Washington",
  "Portland",
  "Santa Clara",
  "Cal Poly",
  "UC Santa Barbara",
  "San Diego State",
  "Loyola Marymount",
  "South Florida",
  "UCF",
  "Florida International",
  "South Carolina",
  "Charlotte",
  "James Madison",
  "William & Mary",
  "UNC Greensboro",
  "VCU",
  "Princeton",
  "Yale",
  "Brown",
  "Harvard",
  "Cornell",
  "Columbia",
  "Boston College",
  "Providence",
  "Seton Hall",
  "Marquette",
  "Xavier",
  "Butler",
  "Denver",
  "Air Force",
  "Memphis",
  "Tulsa",
  "Oral Roberts",
  "Bradley",
  "Missouri State",
  "Western Michigan",
  "Bowling Green",
  "Marshall",
  "West Virginia",
  "Pittsburgh",
  "Temple",
  "Rutgers",
  "Monmouth",
  "Hofstra",
  "Northeastern",
  "Albany",
  "Iona",
  "Fairleigh Dickinson",
  "UMass Lowell",
  "Lipscomb",
  "Belmont",
  "Furman",
  "High Point",
  "Campbell",
  "Dayton",
  "Duquesne",
  "UIC",
  "Drake",
  "Grand Canyon",
  "UNLV",
  "UC Irvine",
  "Cal State Fullerton",
  "Sacramento State",
  "Seattle U",
  "Gonzaga",
  "San Francisco",
  "Pacific"
];
